FROM mcr.microsoft.com/devcontainers/base:ubuntu

ENV NPM_CONFIG_REGISTRY=https://packagefeedproxy.microsoft.io/npm/ \
    PIP_INDEX_URL=https://packagefeedproxy.microsoft.io/pypi/simple \
    PIP_TRUSTED_HOST=packagefeedproxy.microsoft.io
